version: 2.0.{build}
skip_commits:
  message: /NO-BUILD/
  files:
    - docs/*
    - 'LICENSE'
    - 'README.md'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
  - ps: nuget restore
image: Visual Studio 2017
configuration: Release
build:
  parallel: true 
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
test_script:
  - cmd: "\"%USERPROFILE%\\.nuget\\packages\\OpenCover\\4.6.519\\tools\\OpenCover.Console.exe\" -register:user -target:\"%xunit20%\\xunit.console.x86.exe\" -targetargs:\"Grumpy.RipplesMQ.Shared.UnitTests\\bin\\Release\\Grumpy.RipplesMQ.Shared.UnitTests.dll -noshadow\" -output:\"coverage.xml\" -filter:\"+[Grumpy.RipplesMQ.Shared*]* -[Grumpy.RipplesMQ.Shared.UnitTests*|.RipplesMQ.Shared.Messages*]*\""
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 8cdc6c53-279c-4a7e-96e6-a22d32429949
after_build:
  - ps: nuget pack Grumpy.RipplesMQ.Shared\bin\Release\Grumpy.RipplesMQ.Shared.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: Environment
  name: NuGet
